### ISSUE TITLE
Generate Schema and Seeds from existing DB

### ISSUE THREAD

**Issue by R4meau** [miragejs/discuss#1]
Thanks a lot for this amazing tool!

Wow, this is going to revolutionize collaboration between backend and frontend developers. The primary reason for me to use this tool is to be able to let my frontend devs worry only about the frontend and not having to deploy the API themselves.

At the moment, what I do is host a dev server for them and have them all hit the same server for their tests. Which is inherently a bad idea.

Now, I have many existing projects and and they are pretty big. To be able to distribute Mirage for my designers, I'd need to spend about 2-4 hours (rough estimations) building the right Mirage endpoints for them.

At the moment, I start by only building the ones they currently need for their current task until I can cover the whole codebase.

It would be grand to be able to generate the Mirage server right from my MySQL/MongoDB database structures.
It would be even better to be able to add an option to also generate seeds from the DB content.

I'm thinking of a CLI tool that basically behaves like `mysqldump`:
Generate Mirage server from DB
`mirage sync --no-data -h<IP-TO-YOUR-DB-SERVER> -u<YOUR-DB-USERNAME> -p --databases <YOUR-DB-NAME>` > mirage.js

I expect the above to generate the right Mirage server into a mirage.js (that I passed at the end) file that I can import from my App.js file.

Remove the `--no-data` flag to make it generate seeds too.

What do you awesome people think?

**Comment by samselikoff** [comment]
FYI: Transferred this to our new Discuss repo, our new home for open-ended conversations about Mirage!

**Comment by R4meau** [comment]
This is all I needed! Haha, thanks a lot.
