### ISSUE TITLE
routes for related resources

### ISSUE THREAD

**Issue by rvmourik** [miragejs/discuss#53]
Hi there,

Started using MirageJS in one of our Vue projects, but I am having problems with setting up routes to related resources.

I have a message and comments model, with a belongsTo and hasMany, the data is there and with
`alwaysIncludeLinkageData: true` I see the data in the response.

```
      this.get('/messages');
      this.get('/messages/:id');
```

These routes work just fine, but the one below:

      `this.get('/messages/:id/comments');`

Does not work.

How do I achieve this set-up?

Thanks in advance

**Comment by samselikoff** [comment]
Shorthands don't work for nested resources, only top-level, so for this one I would just write it out. 

Something like:

```js
this.get('/messages/:id/comments', (schema, request) => {
  return schema.messages.find(request.params.id).comments
})
```

should do the trick!

**Comment by rvmourik** [comment]
Thanks for the quick reply and solution @samselikoff
